server:
  port: 8080
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql:///hms?serverTimezone=UTC
      url: jdbc:mysql://rm-cn-nwy37ob6e000nfno.rwlb.rds.aliyuncs.com:3306/hms?ServerTimezone=UTC
      username: root
      password: Aa12345678
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.log4jdemo.demo4j.Demo4jApplicationTests: error
  pattern:
    console: "%d - %msg %n"
  file:
    path: ./log